---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by momo.
--- DateTime: 2018/12/28 上午12:21
---
function print_ipairs(t)
    for k, v in ipairs(t) do
        print(k)
    end
end

local t = {}
t[1] = 0
t[100] = 0
print_ipairs(t)