# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AOP_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AOP_demo
  pod "Aspects"

  target 'AOP_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AOP_demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
