# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYCacheDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YYCacheDemo

  pod 'YYCache'

  target 'YYCacheDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYCacheDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
